
library(ggplot2)
# Function to test the topology generated by the niche model
test_niche_topology <- function(pars, num_species) {
  
  # Generate random traits for the species
  traits_mat <- as.data.frame(matrix(NA, nrow = num_species, ncol = 3))
  colnames(traits_mat) <- c("n", "r", "o")
  for (i in 1:num_species) {
    traits_mat[i, ] <- rand_traits_anc(pars)  # Generate random traits
  }
  
  # Generate basal species traits
  basal <- runif(pars$Sbasal, 0, 0.005)
  
  # Compute the interaction network
  L <- get_L_mat(basal, pars, traits_mat)
  
  # Identify trophic levels
  herbivores <- which(colSums(L[1:pars$Sbasal, ]) > 0 & colSums(L[(pars$Sbasal + 1):nrow(L), ]) == 0)
  predators <- which(colSums(L[(pars$Sbasal + 1):nrow(L), ]) > 0 & colSums(L[1:pars$Sbasal, ]) == 0)
  top_predators <- which(colSums(L[(pars$Sbasal + 1):nrow(L), ]) > 0 & rowSums(L) == 0)
  
  # Return the number of top predators
  length(top_predators)
}

# Parameters
set.seed(42)
av_r_values <- seq(0.05, 0.4, length.out = 8)  # Vary av_r values from 0.05 to 0.4
num_species <- 60
num_simulations <- 100

# Create a data frame to store results for all simulations
results_df <- data.frame(av_r = numeric(), top_predators = numeric())

# Loop over av_r values and simulate
for (av_r in av_r_values) {
  pars <- list(Sbasal = 5, Smax = 60, av_r = av_r)
  
  # Run 100 simulations for each av_r value and store number of top predators
  predator_counts <- sapply(1:num_simulations, function(x) test_niche_topology(pars, num_species))
  
  # Combine results into a data frame
  results_df <- rbind(results_df, data.frame(av_r = av_r, top_predators = predator_counts))
}

# Plot the results using boxplot
ggplot(results_df, aes(x = factor(av_r), y = top_predators)) +
  geom_boxplot() +
  xlab("av_r (Niche Range)") +
  ylab("Number of Top Predators") +
  ggtitle("Distribution of Top Predators vs av_r") +
  theme_minimal()



###################

pars <- list(Sbasal = 5, Smax = 60, av_r = 0.1)
test_result <- test_niche_topology(pars, num_species = 60)
print(test_result)


####################
