---
title: "R Notebook"
---

```{r}

library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(igraph)
library(EnvStats)


source(here::here("code/functions/functions_simulation_fw_normdist.R"))
source(here::here("code/functions/functions_simulation_inspection.R"))
source("../functions/functions_metrics_networks.R")
source("../functions/function_plot_mean_div.R")

```


parameters for plotting

```{r}
my.theme<-theme(axis.text=element_text(size=12),
                axis.title = element_text(size = 14),
                legend.position = "top",
                legend.text=element_text(size=10),
                legend.title = element_text(size=12),
                plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
                axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)),
                axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0)))

```



# set general parameters

estab_prob_neutral = 0.5
pars$ext_prob_neutral = 0.0003

Works with neutral at 1, 0.5

```{r}

pars = list()



pars$competition_coefficient = 0.025
pars$Sbasal = 25 # number of basal species
pars$Smax = 1000 # Maximal number of species allowed
pars$Bspe = 4 # Basal species impact on the speciation probality
pars$Bext = 4 # Basal species impact on extinction probability
pars$av_r = 0.185 # 0.2 range of the niche
pars$sd = 0.5*pars$av_r + 0.0001 # Standard deviation of the normal distribution used to calculate the niche optimum trait of a new species
#pars$sd = 0.5*pars$av_r + 0.0001 # Standard deviation of the normal distribution used to calculate the niche optimum trait of a new species

# PROBABILITY OF MUTATION

pars$u_max = 0.23 #0.15 # mutation probability (0.075, )
pars$d = 0.5 # Decrease speed of the establishment probability
pars$I_max = 60 # Maximal number of interactioning species
pars$beta_n =  1 # parameter of the beta distribution 

# STRENGTH OF NEUTRAL-DRIVEN EVOLUTION

pars$SN = 1 # strength for neutral-driven evolution

# PROBABILITY OF ESTABLISHMENT

# strength of selection-driven selection is 1 - SN
pars$estab_prob_neutral = rep(0.5, pars$Smax) # neutral probability of establishment

# Facilitation & Foodweb

pars$u_0pos = 1  
pars$u_1pos = -1 
pars$a_upos = 0.45 

# PROBABILITY OF EXTINCTION

pars$ext_prob_neutral = 0.03 # neutral probability of extinction

# Competition

pars$e_0neg = 0.1 #0.15 # Asymptotic extinction probability with infinite negative interactions
pars$a_eneg = 0.025 # Shape of the exponential decay of the negative extinction - interaction relationship
pars$e_1neg = -pars$e_0neg  # Extinction probability with absence of interactions

# Facilitation & Foodweb

pars$e_0pos = 0.075 
pars$e_1pos = 5.19 
pars$a_epos = 1.2 

```


# parameters simulation

```{r}
nsteps =  250
n_sims = 2

```




# Simulation

```{r}

pars$int = 2

list_results <- list()
#list_adj_matrix.f <- list()

for (i in 1:n_sims) {
  
  #seed <- set.seed(50)
  seed <- sample.int(80000, 1)
  
  simulation <- sim_model_bif_fw(seed = seed, 
                          pars, 
                          nsteps = nsteps)
  
  res <- list(
    seed = seed,
    parameters = pars, 
    presence_matrix = simulation$pres, 
    traits_df = simulation$traits,
    parentage_matrix = simulation$anc,
    extinxction_matrix = simulation$extinct, 
    network_list = simulation$L_list,
    anc_dist_table = simulation$dist_anc, 
    list_anc_dist = simulation$list_dist_anc
  ) # Record results from the simulation
  
  list_results[[i]] <- res
}

```


```{r}
compute_div_curves_from_list_res(list_results)[[1]]
```

```{r}
inspect_simulation_fw(simulation_data = list_results[[1]])
```

